# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: vote-app
type: Opaque
stringData:
  username: postgres
  password: postgresspasswordadmin
---
