# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: vote-app
type: Opaque
stringData:
  password: redisspasswordadmin
---
