apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: vote-app
spec:
  selector:
    matchLabels:
      app: result-deployment
  template:
    metadata:
      labels:
        app: result-deployment
    spec:
      containers:
      - name: result-deployment
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80
